### ISSUE TITLE
Redirect user to OTP verification page if email hasn't been verified yet

### ISSUE THREAD

**Issue by ananyatewari** [kalviumcommunity/S59_Ananya_Capstone_Feedback_Finesse#63]
I have implemented an email OTP verification system using Nodemailer with server-side rendering in the **/signup** route of my application. 
However, during the login process, I want to ensure that users are verified. If a user isn't verified, they should be redirected to the OTP verification page, where a new email with an OTP will be sent to them to complete the verification process. 

Please make the required changes in the **/login** route.

**Comment by Satyamsharmahp36** [comment]
Hi , I have worked on this concept earlier, can I work on this ?

**Comment by ananyatewari** [comment]
Sure

I think you might need the env file to fix this. Do you mind giving me your mail id so that I could forward it to you ?

**Comment by Satyamsharmahp36** [comment]
sure , satyam.sharma@kalvium.community

**Comment by Satyamsharmahp36** [comment]
Can you review this PR

**Comment by ananyatewari** [comment]
Reviewed and merged without any conflicts.

Thanks for the contribution.
