### ISSUE TITLE
Add media query to the About page

### ISSUE THREAD

**Issue by ananyatewari** [kalviumcommunity/S59_Ananya_Capstone_Feedback_Finesse#65]
A media query enhancement is required for the About page to optimize the overall UI experience. 

Prior to submitting a pull request, consider the following points:
 
   1. Ensure the media queries are tailored to accommodate various screen dimensions, including mobile, tablet views, etc.
   2. Conduct testing through rigorous element inspection on your local machine.
   3. Modifications will need to be applied to two files, specifically **_About.css_** and **_Coffee.jsx_**.

**Comment by Swasti008** [comment]
Can I contribute to this issue?

**Comment by ananyatewari** [comment]
Sure, you can go ahead

**Comment by Swasti008** [comment]
#66 Can you review this PR as I have added the media query to about.css

**Comment by ananyatewari** [comment]
Reviewed and merged #66 

Thanks for the contribution
